### PR TITLE
Fixed #230 - Implemented JsonObject deep merge

### LINKED ISSUE #230: Can't configure single property of HttpRepositoryConnector
When overriding `HttpRepositoryConnector` configuration via starter JSON config I had to define **all** overridden properties, not only one that I wanted to override.
Example:
```json
    "knotx:io.knotx.HttpRepositoryConnector": {
      "options": {
        "config": {
          "clientDestination": {
            "domain": "my.custom.domain"
          }
        }
      }
    }
```
This ended with `NPE` @ `RepositoryConnectorProxyImpl:87`.

After changing override to:
```json
    "knotx:io.knotx.HttpRepositoryConnector": {
      "options": {
        "config": {
          "clientDestination": {
            "port": 3001,
            "domain": "my.custom.domain"
          }
        }
      }
    }
```

Connector worked fine.

Stacktrace:
```

2017-01-20 08:47:17 [vert.x-eventloop-thread-2] ERROR i.v.c.e.impl.HandlerRegistration - Failed to handleMessage
java.lang.NullPointerException: null
        at io.knotx.repository.impl.RepositoryConnectorProxyImpl.process(RepositoryConnectorProxyImpl.java:87)
        at io.knotx.proxy.RepositoryConnectorProxyVertxProxyHandler.handle(RepositoryConnectorProxyVertxProxyHandler.java:128)
        at io.knotx.proxy.RepositoryConnectorProxyVertxProxyHandler.handle(RepositoryConnectorProxyVertxProxyHandler.java:53)
        at io.vertx.core.eventbus.impl.HandlerRegistration.deliver(HandlerRegistration.java:212)
        at io.vertx.core.eventbus.impl.HandlerRegistration.handle(HandlerRegistration.java:191)
        at io.vertx.core.eventbus.impl.EventBusImpl.lambda$deliverToHandler$3(EventBusImpl.java:503)
        at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:316)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:418)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:440)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:873)
        at java.lang.Thread.run(Unknown Source)
2017-01-20 08:47:17 [vert.x-eventloop-thread-2] ERROR io.vertx.core.impl.ContextImpl - Unhandled exception
java.lang.NullPointerException: null
        at io.knotx.repository.impl.RepositoryConnectorProxyImpl.process(RepositoryConnectorProxyImpl.java:87)
        at io.knotx.proxy.RepositoryConnectorProxyVertxProxyHandler.handle(RepositoryConnectorProxyVertxProxyHandler.java:128)
        at io.knotx.proxy.RepositoryConnectorProxyVertxProxyHandler.handle(RepositoryConnectorProxyVertxProxyHandler.java:53)
        at io.vertx.core.eventbus.impl.HandlerRegistration.deliver(HandlerRegistration.java:212)
        at io.vertx.core.eventbus.impl.HandlerRegistration.handle(HandlerRegistration.java:191)
        at io.vertx.core.eventbus.impl.EventBusImpl.lambda$deliverToHandler$3(EventBusImpl.java:503)
        at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:316)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:418)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:440)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:873)
        at java.lang.Thread.run(Unknown Source)
```

### PR DESCRIPTION
**Pull request by marcinczeczko**

### CODE REVIEW

File: knotx-core/src/test/java/io/knotx/util/JsonObjectUtilTest.java [hunk 1]
```diff
@@ -0,0 +1,147 @@
...
+  public void whenSourceObjectMergedWithNewObject_expectNewObjectAdded() {
+    JsonObject updateAndAdd = new JsonObject()
+        .put("config", new JsonObject()
+            .put("clientOptions", new JsonObject()
+                .put("a", "aaa")
+                .put("b", 1234)));
+
+    JsonObjectUtil.deepMerge(source, updateAndAdd);
+
+    assertThat(
```
Comment (toniedzwiedz) [inline knotx-core/src/test/java/io/knotx/util/JsonObjectUtilTest.java]: Nice, I like `assertThat` 👍

Comment (marcinczeczko) [inline knotx-core/src/test/java/io/knotx/util/JsonObjectUtilTest.java]: thanks :)
